# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170413_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='filee',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
